### ISSUE TITLE
Facebook icon too small to show count

### ISSUE THREAD

**Issue by Armistral** [bcoughlan/TwitterFBLike#4]
Hello,

I am trying to use this extension on my mediawiki site however when I use the small version the # of FB Recommendations is hidden and in any size the Tweeting does not update the count of tweets.  I am using version 1.17.0 of MediaWiki.  The behavior shows up in Chrome, FF and IE.

You can see this by looking at my site:  http://www.wesolver.org/wiki/Main_Page

Anything you can do would be much appreciated, I like the widget just would like it to work with the current version as intended.

Regards,

Armistral

**Comment by bcoughlan** [comment]
Hi Armistral,

I've fixed the Recommends issue in version 0.9: https://github.com/downloads/bcoughlan/Extension-TwitterFBLike/TwitterFBLike-0.9.zip (I rolled back the version numbers, the last one was 1.0 which has been deleted).

Apparently if the Facebook counter is at 0 the number doesn't show up. I made it wider and swapped the Tweet and FB buttons around. I also changed the style of the big buttons, see mediawiki for details: http://www.mediawiki.org/wiki/Extension:TwitterFBLike

I made another issue for the Tweet count problem (see #5), which I will look at over the weekend.
